"use client";"use client";"use client";

































































































































































































































































































































}  };    pageSize: PAGE_SIZE,    page,    total: filtered.length,    digests: sliced,  return {  const sliced = filtered.slice(start, start + PAGE_SIZE);  const start = (page - 1) * PAGE_SIZE;    filter === "all" ? allDigests : allDigests.filter((d) => d.type === filter);  const filtered =  }    }      });        preview: `This week in crypto: A comprehensive look at the biggest stories, market movements, DeFi developments, and regulatory changes. Includes AI-generated trend analysis and forward-looking predictions.`,        storyCount: 40 + Math.floor(Math.random() * 20),        type: "weekly",        title: `Weekly Wrap: ${date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,        date: date.toISOString(),        id: `weekly-${dateStr}`,      allDigests.push({    if (dayOfWeek === 0) {    // Weekly digest on Sundays    });      preview: `Today's top stories: Bitcoin ${Math.random() > 0.5 ? "rallies" : "consolidates"} as market ${Math.random() > 0.5 ? "sentiment improves" : "awaits key data"}. Ethereum ecosystem sees continued growth with new DeFi protocols launching. Regulatory updates from major economies continue to shape the landscape.`,      storyCount: 15 + Math.floor(Math.random() * 10),      type: "daily",      title: `Crypto Daily: ${date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,      date: date.toISOString(),      id: `daily-${dateStr}`,    allDigests.push({    // Daily digest every day    const dayOfWeek = date.getDay();    const dateStr = date.toISOString().split("T")[0];    date.setDate(date.getDate() - i);    const date = new Date(now);  for (let i = 0; i < 30; i++) {  const now = new Date();  const allDigests: DigestEntry[] = [];): DigestResponse {  filter: "all" | "daily" | "weekly"  page: number,function generateFallbackDigests(/* ─── Fallback data for when the API is unavailable ─── */}  );    </div>      )}        </div>          </Button>            Next          >            disabled={page === totalPages || loading}            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}            size="sm"            variant="outline"          <Button          </span>            Page {page} of {totalPages}          <span className="text-sm text-[var(--color-text-tertiary)] px-3">          </Button>            Previous          >            disabled={page === 1 || loading}            onClick={() => setPage((p) => Math.max(1, p - 1))}            size="sm"            variant="outline"          <Button        <div className="flex items-center justify-center gap-2 mt-6">      {totalPages > 1 && (      {/* Pagination */}      )}        </div>          })}            );              </div>                )}                  </div>                    )}                      </div>                        {expandedContent[digest.id] || digest.preview || ""}                      <div className="py-4 text-sm text-[var(--color-text-secondary)] leading-relaxed whitespace-pre-line">                    ) : (                      </div>                        Loading digest content…                        <Loader2 className="h-4 w-4 animate-spin" />                      <div className="flex items-center gap-2 py-4 text-sm text-[var(--color-text-tertiary)]">                    {isLoadingThis ? (                  <div className="px-4 pb-4 pt-0 border-t border-[var(--color-border)]">                {isExpanded && (                </button>                  </div>                    </span>                      {digest.storyCount} stories                    <span className="text-xs text-[var(--color-text-tertiary)] hidden sm:inline">                    </Badge>                      {digest.type}                    >                      )}                          : ""                          ? "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400"                        digest.type === "weekly"                        "text-[10px]",                      className={cn(                    <Badge                  <div className="flex items-center gap-2 shrink-0">                  </h3>                    {digest.title}                  <h3 className="text-sm font-medium text-[var(--color-text-primary)] truncate flex-1 min-w-0">                  </div>                    </time>                      })}                        year: "numeric",                        day: "numeric",                        month: "short",                      {new Date(digest.date).toLocaleDateString("en-US", {                    <time>                    <Calendar className="h-3.5 w-3.5" />                  <div className="flex items-center gap-2 text-xs text-[var(--color-text-tertiary)] shrink-0">                  )}                    <ChevronRight className="h-4 w-4 text-[var(--color-text-tertiary)] shrink-0" />                  ) : (                    <ChevronDown className="h-4 w-4 text-[var(--color-text-tertiary)] shrink-0" />                  {isExpanded ? (                >                  className="w-full flex items-center gap-4 p-4 text-left cursor-pointer hover:bg-[var(--color-surface-secondary)] rounded-lg transition-colors"                  onClick={() => toggleExpand(digest)}                  type="button"                <button              >                )}                  isExpanded && "border-[var(--color-accent)]/40"                  "rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] transition-colors",                className={cn(                key={digest.id}              <div            return (            const isLoadingThis = loadingContent === digest.id;            const isExpanded = expandedId === digest.id;          {digests.map((digest) => {        <div className="space-y-2">      ) : (        </div>          </p>            No digests found for the selected filter.          <p className="text-sm text-[var(--color-text-secondary)]">          <FileText className="h-8 w-8 text-[var(--color-text-tertiary)] mx-auto mb-3" />        <div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-secondary)] p-8 text-center">      ) : digests.length === 0 ? (        </div>          ))}            </div>              </div>                <Skeleton className="h-4 w-16 ml-auto" />                <Skeleton className="h-5 w-64" />                <Skeleton className="h-4 w-28" />              <div className="flex items-center gap-4">            >              className="rounded-lg border border-[var(--color-border)] p-4"              key={i}            <div          {Array.from({ length: 5 }).map((_, i) => (        <div className="space-y-3">      {loading ? (      {/* Digest List */}      </div>        ))}          </button>            {f === "all" ? "All" : f === "daily" ? "Daily" : "Weekly"}          >            )}                : "bg-[var(--color-surface-secondary)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-tertiary)]"                ? "bg-[var(--color-accent)] text-white"              filter === f              "px-4 py-1.5 rounded-full text-sm font-medium transition-colors cursor-pointer",            className={cn(            onClick={() => handleFilterChange(f)}            type="button"            key={f}          <button        {(["all", "daily", "weekly"] as const).map((f) => (      <div className="flex items-center gap-2 mb-6">      {/* Filter Tabs */}    <div>  return (  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));  };    }      }        setLoadingContent(null);      } finally {        }));            "Unable to load digest content. Please try again later.",            digest.preview ??          [digest.id]:          ...prev,        setExpandedContent((prev) => ({      } catch {        }          }));              "Full digest content is available in the email edition. Subscribe above to receive each digest directly in your inbox.",              digest.preview ??            [digest.id]:            ...prev,          setExpandedContent((prev) => ({        } else {          }));            [digest.id]: data.content ?? data.summary ?? digest.preview ?? "",            ...prev,          setExpandedContent((prev) => ({          const data = await res.json();        if (res.ok) {        const res = await fetch(`/api/digest/${digest.id}`);      try {      setLoadingContent(digest.id);    if (!expandedContent[digest.id]) {    setExpandedId(digest.id);    }      return;      setExpandedId(null);    if (expandedId === digest.id) {  const toggleExpand = async (digest: DigestEntry) => {  };    setExpandedId(null);    setPage(1);    setFilter(newFilter);  const handleFilterChange = (newFilter: "all" | "daily" | "weekly") => {  }, [fetchDigests]);    fetchDigests();  useEffect(() => {  }, [page, filter]);    }      setLoading(false);    } finally {      setTotal(fallback.total);      setDigests(fallback.digests);      const fallback = generateFallbackDigests(page, filter);      // Use fallback demo data when API unavailable    } catch {      setTotal(data.total ?? 0);      setDigests(data.digests ?? []);      const data: DigestResponse = await res.json();      if (!res.ok) throw new Error("Failed to fetch");      const res = await fetch(`/api/digest?${params}`);      if (filter !== "all") params.set("type", filter);      });        limit: String(PAGE_SIZE),        page: String(page),      const params = new URLSearchParams({    try {    setLoading(true);  const fetchDigests = useCallback(async () => {  const [loadingContent, setLoadingContent] = useState<string | null>(null);  >({});    Record<string, string>  const [expandedContent, setExpandedContent] = useState<  const [expandedId, setExpandedId] = useState<string | null>(null);  const [loading, setLoading] = useState(true);  const [total, setTotal] = useState(0);  const [digests, setDigests] = useState<DigestEntry[]>([]);  const [page, setPage] = useState(1);  const [filter, setFilter] = useState<"all" | "daily" | "weekly">("all");export default function DigestArchive() {const PAGE_SIZE = 10;}  pageSize: number;  page: number;  total: number;  digests: DigestEntry[];interface DigestResponse {}  preview?: string;  storyCount: number;  type: "daily" | "weekly";  title: string;  date: string;  id: string;interface DigestEntry {import { cn } from "@/lib/utils";import { Skeleton } from "@/components/ui/Skeleton";import { Badge } from "@/components/ui/Badge";import { Button } from "@/components/ui/Button";} from "lucide-react";  Loader2,  FileText,  Calendar,  ChevronRight,  ChevronDown,import {import { useState, useEffect, useCallback } from "react";


















































































































































































































































}  });    };        "A comprehensive overview of the day's most important cryptocurrency developments, market movements, and regulatory updates.",      summary:      stories: Math.floor(Math.random() * 15) + 5,      type: i % 7 === 0 ? "weekly" : "daily",      date: date.toISOString(),      title: `Crypto ${i % 7 === 0 ? "Weekly" : "Daily"}: ${date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,      id: `fallback-${i}`,    return {    date.setDate(date.getDate() - i);    const date = new Date(now);  return Array.from({ length: 7 }).map((_, i) => {  const now = new Date();function generateFallbackDigests(): DigestEntry[] {/** Generate fallback digests when API is unavailable */}  );    </div>      )}        </div>          </Button>            Next          >            disabled={!hasMore}            onClick={() => setPage((p) => p + 1)}            size="sm"            variant="outline"          <Button          </span>            Page {page}          <span className="text-sm text-[var(--color-text-tertiary)]">          </Button>            Previous          >            disabled={page <= 1}            onClick={() => setPage((p) => Math.max(1, p - 1))}            size="sm"            variant="outline"          <Button        <div className="flex items-center justify-center gap-3 mt-6">      {filtered.length > 0 && (      {/* Pagination */}      )}        </div>          ))}            </Card>              )}                </div>                  )}                    </ul>                      ))}                        </li>                          {h}                          <span className="mt-1 h-1 w-1 rounded-full bg-[var(--color-accent)] shrink-0" />                        >                          className="flex items-start gap-2 text-xs text-[var(--color-text-secondary)]"                          key={i}                        <li                      {d.highlights.map((h, i) => (                    <ul className="mt-3 space-y-1.5">                  {d.highlights && d.highlights.length > 0 && (                  </p>                    {d.summary}                  <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed mt-3">                <div className="px-4 pb-4 border-t border-[var(--color-border)]">              {expandedId === d.id && d.summary && (              {/* Expanded content */}              </button>                </CardContent>                  )}                    <ChevronDown className="h-4 w-4 text-[var(--color-text-tertiary)] shrink-0" />                  ) : (                    <ChevronUp className="h-4 w-4 text-[var(--color-text-tertiary)] shrink-0" />                  {expandedId === d.id ? (                  </Badge>                    {d.type}                  >                    className="shrink-0"                    variant={d.type === "weekly" ? "outline" : "default"}                  <Badge                  </div>                    </div>                      )}                        </span>                          {d.stories} stories                          <FileText className="h-3 w-3" />                        <span className="flex items-center gap-1">                      {d.stories > 0 && (                      </time>                        })}                          year: "numeric",                          day: "numeric",                          month: "short",                        {new Date(d.date).toLocaleDateString("en-US", {                      <time>                    <div className="flex items-center gap-3 text-xs text-[var(--color-text-tertiary)] mt-0.5">                    </p>                      {d.title}                    <p className="font-semibold text-sm text-[var(--color-text-primary)] truncate">                  <div className="flex-1 min-w-0">                  </div>                    <Calendar className="h-5 w-5 text-[var(--color-accent)]" />                  <div className="h-10 w-10 rounded-lg bg-[var(--color-surface-secondary)] flex items-center justify-center shrink-0">                <CardContent className="p-4 flex items-center gap-4">              >                className="w-full text-left"                onClick={() => toggleExpand(d.id)}              <button            <Card key={d.id} className="overflow-hidden">          {filtered.map((d) => (        <div className="space-y-3">      ) : (        </p>          No digests available yet. Subscribe to be notified when the first one drops!        <p className="text-center py-8 text-[var(--color-text-tertiary)]">      {filtered.length === 0 ? (      {/* Digest list */}      </div>        ))}          </button>            {f === "all" ? "All" : f === "daily" ? "Daily" : "Weekly"}          >            )}                : "bg-[var(--color-surface-secondary)] text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]"                ? "bg-[var(--color-accent)] text-white"              filter === f              "px-3 py-1.5 text-sm font-medium rounded-lg transition-colors",            className={cn(            onClick={() => handleFilterChange(f)}            key={f}          <button        {(["all", "daily", "weekly"] as const).map((f) => (      <div className="flex gap-2 mb-4">      {/* Filter tabs */}    <div>  return (  }    );      </div>        ))}          </div>            <Skeleton className="h-6 w-16 rounded-full" />            </div>              <Skeleton className="h-3 w-48" />              <Skeleton className="h-5 w-3/4" />            <div className="flex-1 space-y-2">            <Skeleton className="h-10 w-10 rounded" />          >            className="flex items-center gap-4 p-4 rounded-lg border border-[var(--color-border)]"            key={i}          <div        {Array.from({ length: 5 }).map((_, i) => (      <div className="space-y-3">    return (  if (loading) {  const filtered = digests;  };    setExpandedId((prev) => (prev === id ? null : id));  const toggleExpand = (id: string) => {  };    setExpandedId(null);    setPage(1);    setFilter(newFilter);  const handleFilterChange = (newFilter: FilterType) => {  }, [fetchDigests]);    fetchDigests();  useEffect(() => {  }, [page, filter]);    }      setLoading(false);    } finally {      setHasMore(false);      setDigests(generateFallbackDigests());      // Show fallback digests on error    } catch {      setHasMore(items.length >= perPage);      setDigests(items);      );        })          highlights: d.highlights as string[] | undefined,          summary: (d.summary as string) ?? (d.description as string) ?? undefined,          stories: (d.stories as number) ?? (d.storyCount as number) ?? 0,          type: (d.type as "daily" | "weekly") ?? "daily",          date: (d.date as string) ?? new Date().toISOString(),          title: (d.title as string) ?? "Crypto Digest",          id: (d.id as string) ?? `digest-${page}-${i}`,        (d: Record<string, unknown>, i: number) => ({      const items: DigestEntry[] = (data?.digests ?? data?.items ?? []).map(      const data = await res.json();      if (!res.ok) throw new Error("Failed to fetch");      const res = await fetch(`/api/digest?${params}`);      if (filter !== "all") params.set("type", filter);      });        limit: String(perPage),        page: String(page),      const params = new URLSearchParams({    try {    setLoading(true);  const fetchDigests = useCallback(async () => {  const perPage = 10;  const [hasMore, setHasMore] = useState(true);  const [expandedId, setExpandedId] = useState<string | null>(null);  const [page, setPage] = useState(1);  const [filter, setFilter] = useState<FilterType>("all");  const [loading, setLoading] = useState(true);  const [digests, setDigests] = useState<DigestEntry[]>([]);export default function DigestArchive() {type FilterType = "all" | "daily" | "weekly";}  highlights?: string[];  summary?: string;  stories: number;  type: "daily" | "weekly";  date: string;  title: string;  id: string;interface DigestEntry {import { ChevronDown, ChevronUp, Calendar, FileText } from "lucide-react";import { cn } from "@/lib/utils";import { Skeleton } from "@/components/ui/Skeleton";import { Button } from "@/components/ui/Button";import { Badge } from "@/components/ui/Badge";import { Card, CardContent } from "@/components/ui/Card";import { useState, useEffect, useCallback } from "react";
































































}  );    </div>      )}        </div>          </Button>            <ChevronRight className="h-4 w-4" />          >            aria-label="Next page"            onClick={() => setPage(page + 1)}            disabled={page >= totalPages - 1}            size="icon"            variant="outline"          <Button          </span>            {page + 1} / {totalPages}          <span className="text-sm text-[var(--color-text-secondary)]">          </Button>            <ChevronLeft className="h-4 w-4" />          >            aria-label="Previous page"            onClick={() => setPage(page - 1)}            disabled={page === 0}            size="icon"            variant="outline"          <Button        <div className="flex items-center justify-center gap-2 pt-2">      {totalPages > 1 && (      {/* Pagination */}      </div>        ))}          </Card>            </CardContent>              )}                </div>                  </p>                    {digest.preview}                  <p className="text-sm text-[var(--color-text-secondary)]">                <div className="mt-3 border-t border-[var(--color-border)] pt-3">              {expanded === digest.date && (              </div>                </Badge>                  {digest.type}                <Badge variant={digest.type === "weekly" ? "trading" : "default"}>                </div>                  </div>                    <span>{digest.stories} stories</span>                    </span>                      {digest.date}                      <Calendar className="h-3 w-3" />                    <span className="flex items-center gap-1">                  <div className="flex items-center gap-3 text-xs text-[var(--color-text-tertiary)]">                  </div>                    </p>                      {digest.title}                    <p className="text-sm font-semibold text-[var(--color-text-primary)] truncate">                    <FileText className="h-4 w-4 text-[var(--color-accent)] shrink-0" />                  <div className="flex items-center gap-2 mb-1">                <div className="flex-1 min-w-0">              <div className="flex items-center justify-between gap-4">            <CardContent className="p-4">
          >
            onClick={() => setExpanded(expanded === digest.date ? null : digest.date)}
            className={cn("transition-shadow hover:shadow-md cursor-pointer")}
            key={digest.date + digest.type}
          <Card
        {paginated.map((digest) => (
      <div className="space-y-3">
      {/* Digest list */}

      </div>
        ))}
          </Button>
            {f === "all" ? "All" : f === "daily" ? "Daily" : "Weekly"}
          >
            onClick={() => { setFilter(f); setPage(0); }}
            size="sm"
            variant={filter === f ? "default" : "outline"}
            key={f}
          <Button
        {(["all", "daily", "weekly"] as const).map((f) => (
      <div className="flex gap-2">
      {/* Filter tabs */}
    <div className="space-y-4">
  return (

  const paginated = filtered.slice(page * PER_PAGE, (page + 1) * PER_PAGE);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PER_PAGE));
  const filtered = filter === "all" ? MOCK_DIGESTS : MOCK_DIGESTS.filter((d) => d.type === filter);

  const [expanded, setExpanded] = useState<string | null>(null);
  const [page, setPage] = useState(0);
  const [filter, setFilter] = useState<"all" | "daily" | "weekly">("all");
export default function DigestArchive() {

const PER_PAGE = 5;

];
  { date: "2026-02-21", title: "Crypto Daily: February 21, 2026", stories: 8, type: "daily", preview: "Ethereum gas fees drop to 3 gwei as blob transactions reduce L1 congestion." },
  { date: "2026-02-22", title: "Crypto Daily: February 22, 2026", stories: 14, type: "daily", preview: "South Korea FSC releases institutional crypto guidelines. BTC funding rates turn negative." },
  { date: "2026-02-16", title: "Crypto Weekly: Feb 10–16, 2026", stories: 38, type: "weekly", preview: "Weekly roundup: Regulatory clarity in US, Solana DePIN growth, and stablecoin market expands." },
  { date: "2026-02-24", title: "Crypto Daily: February 24, 2026", stories: 13, type: "daily", preview: "NFT market sees revival with new collections on Base and Arbitrum. Gaming tokens rally." },
  { date: "2026-02-25", title: "Crypto Daily: February 25, 2026", stories: 9, type: "daily", preview: "Gold and Bitcoin rally as Fed signals further rate cuts. DXY index drops below 103." },
  { date: "2026-02-26", title: "Crypto Daily: February 26, 2026", stories: 11, type: "daily", preview: "Hong Kong extends retail crypto access to tokenized securities. UAE VARA issues new DeFi guidelines." },
  { date: "2026-02-23", title: "Crypto Weekly: Feb 17–23, 2026", stories: 42, type: "weekly", preview: "Weekly roundup: BTC up 8%, ETH staking hits 30M, DeFi TVL crosses $200B, and more." },
  { date: "2026-02-27", title: "Crypto Daily: February 27, 2026", stories: 10, type: "daily", preview: "Solana ecosystem sees surge in DeFi activity. Bitcoin mining difficulty reaches all-time high." },
  { date: "2026-02-28", title: "Crypto Daily: February 28, 2026", stories: 15, type: "daily", preview: "SEC approves spot Ethereum ETF options. MiCA stablecoin rules take effect across the EU." },
  { date: "2026-03-01", title: "Crypto Daily: March 1, 2026", stories: 12, type: "daily", preview: "Bitcoin surges past $95K as institutional demand accelerates. Ethereum Layer 2 TVL hits new record." },
const MOCK_DIGESTS: DigestEntry[] = [

}
  preview: string;
  type: "daily" | "weekly";
  stories: number;
  title: string;
  date: string;
interface DigestEntry {

import { Calendar, ChevronLeft, ChevronRight, FileText } from "lucide-react";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";import { useState } from "react";